### PR TITLE
Support React 18

### PR DESCRIPTION
**Pull request by andy-todd-dev**

### CODE REVIEW

**Comment by jorisre** [comment]
Thank you for the PR, does the example works with your local setup ? It seems to be broken during deployment with Vercel

**Comment by andy-todd-dev** [comment]
> Thank you for the PR, does the example works with your local setup ? It seems to be broken during deployment with Vercel

Hi, I’m using the default Codespaces env. From a fresh one the following steps all appear to work as expected:
 - `yarn install`
 - `yarn run build`
 - `yarn test`
 - `cd example`
 - `yarn install`
 - `yarn run dev`
 - I’ve tested the running dev mode in Safari for iOS (doesn’t support wake-lock api) and Chrome for Android (does support wake-lock api)

I can’t seem to view Varcel (404 error), but if you could forward me the error output I’m happy to investigate. Or does it have differing build steps I could try?

**Comment by andy-todd-dev** [comment]
Think we're there now. Didn't realise the `yarn run dev` step would skip `tsc`

**Comment by jorisre** [comment]
PR merged ! Thank you @andy-todd-dev for your contribution :)

**Pull request merged**
